swagger: "2.0"
info:
  version: tb-pipeline-dev-0-001
  title: "TB Pipeline 2 API"
  description: User API spec for the pipeline migration project.
  contact:
    name: TravelBytes Team
    email: info@travelbytes.biz
    url: http://travelbytes.biz
host: tb-pipeline-dev.appspot.com
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:

  # Transform Component
  /qi/transform/xml:
    post:
      tags:
        - transform
      summary: Transforms XML using XSLT from a subscriber push message
      operationId: transformXml
      parameters:
        - name: token
          in: query
          description: Push message token for message publishing
          required: true
          type: string
        - name: loginBody
          in: body
          required: true
          description: Standard push message with id property in data
          schema:
            $ref: "#/definitions/PushMessage"
      responses:
        200:
          description: |
            Transform successful and message published to topic if there is an empty resonse
            Coded responses implies a failure during the transform process
          schema:
            $ref: '#/definitions/MessageResponse'

  # Enrich Component
  /qi/enrich/xml:
    post:
      tags:
        - enrich
      summary: Enriches XML using module services from a subscriber push message
      operationId: enrichXml
      parameters:
        - name: token
          in: query
          description: Push message token for message publishing
          required: true
          type: string
        - name: loginBody
          in: body
          required: true
          description: Standard push message with id property in data
          schema:
            $ref: "#/definitions/PushMessage"
      responses:
        200:
          description: |
            Enrich successful and message published to topic if there is an empty resonse
            Coded responses implies a failure during the transform process
          schema:
            $ref: '#/definitions/MessageResponse'


# Object Definitions
definitions:
  EmptyResponse:
    description: No data being returned
    type: object
  
  MessageResponse:
    type: object
    required:
     - code
     - message
    properties:
      code:
        description: Message code
        type: string
      message:
        description: Message description
        type: string

  PushMessage:
    description: Push message sent to a subscriber
    type: object
    required:
      - subscription
      - message
    properties:
      subscripton:
        description: Full subscription string as on GCP
        type: string
      message:
        $ref: '#/definitions/PushSubMessage'
            
  PushSubMessage:
    description: Message payload published together during a PubSub. Either the data or attributes property must be populated
    type: object
    properties:
      data:
        description: Data sent in b64 encoded format
        type: string
      attributes: 
        description: Object consisting of key/value pairs, if data is empty, this must be populated
        type: object
      messageId:
        description: Id of the published message, this is autopopulated by the publisher server
        type: number
      publishTime:
        description: Time of published message, this is autopopulated by the publisher server
        type: string
        format: date-time
      force:
        description: Force reprocessing of xml transformation regardless of status
        type: boolean